version: "3"
services:
  back:
    build: ./back/
    image: dontmakemewait.azurecr.io/dmmw-back:0.1
    volumes:
      - ./back/:/app
    restart: always

  front:
    build: ./front/
    image: dontmakemewait.azurecr.io/dmmw-front:0.1
    volumes:
      - ./front/:/app
    ports:
      - "80:80"
    restart: always
